### PR TITLE
event marshal JSON

### PR DESCRIPTION
**Pull request by barkyq**
moved escapeString into helpers.go and changed the MarshalJSON method for event to use the correct string escaping

### CODE REVIEW

**Comment by barkyq** [comment]
this should end the saga of #28

**Comment by fiatjaf** [comment]
So you're doing an entirely custom JSON marshaler? Can you remove fastjson then?

**Comment by barkyq** [comment]
fastjson is still used for the fast unmarshaling. The problem with fastjson is that it uses `strconv.Quote` when escaping strings which does not seem to follow the rules of RFC8259, and was leading to signature verification problems with certain characters. Fastjson does seem to have a RFC8259 compliant string "unescaping" function.

I tried to write my own JSON unmarshaler, but it was much slower than the current one using fastjson...

**Comment by barkyq** [comment]
hooray!

**Pull request merged**
