### PR TITLE
add nrelay

### PR DESCRIPTION
**Pull request by mattn**
I'll add PR for nak in later

### CODE REVIEW

**Comment by mattn** [comment]
I have to add EncodeRelay too.

**Comment by mattn** [comment]
add encode and tests

**Comment by fiatjaf** [comment]
Can we not have this? I hate it. We should remove it from the NIP. Using the hostname directly is better.

Or do you have a reason for using this weird encoding thing?

**Comment by fiatjaf** [comment]
Just opened this: https://github.com/nostr-protocol/nips/pull/1375

**Comment by mattn** [comment]
>Or do you have a reason for using this weird encoding thing?

No. I also want to remove if possible

**Comment by mattn** [comment]
nrelay no longer exists.

**Pull request closed without merging**
