### PR TITLE
Switch to gobwas/ws, add compression

### PR DESCRIPTION
**Pull request by wozuo**

### CODE REVIEW

**Comment by fiatjaf** [comment]
This one is promising.

**Comment by fiatjaf** [comment]
Seems to be working flawlessly. Did you have experience with this library before?

**Comment by fiatjaf** [comment]
Actually I'm getting more relays disconnecting with this than before. It must be something related to the pingpong policy. I'll take a look tomorrow unless you want to.

I'm running this code:

```go
package main

import (
	"context"
	"fmt"
	"sync"

	"github.com/nbd-wtf/go-nostr"
)

var relays = []string{
	nostr.NormalizeURL("wss://atlas.nostr.land"),
	nostr.NormalizeURL("wss://brb.io"),
	nostr.NormalizeURL("wss://eden.nostr.land"),
	nostr.NormalizeURL("wss://lightningrelay.com"),
	nostr.NormalizeURL("wss://no.str.cr"),
	nostr.NormalizeURL("wss://nos.lol"),
	nostr.NormalizeURL("wss://nostr-pub.wellorder.net"),
	nostr.NormalizeURL("wss://nostr.fmt.wiz.biz"),
	nostr.NormalizeURL("wss://nostr.inosta.cc"),
	nostr.NormalizeURL("wss://nostr.kollider.xyz"),
	nostr.NormalizeURL("wss://nostr.member.cash"),
	nostr.NormalizeURL("wss://nostr.milou.lol"),
	nostr.NormalizeURL("wss://nostr.mom"),
	nostr.NormalizeURL("wss://nostr.pleb.network"),
	nostr.NormalizeURL("wss://nostr.uselessshit.co"),
	nostr.NormalizeURL("wss://nostr.wine"),
	nostr.NormalizeURL("wss://nostr1.current.fyi"),
	nostr.NormalizeURL("wss://offchain.pub"),
	nostr.NormalizeURL("wss://powrelay.xyz"),
	nostr.NormalizeURL("wss://puravida.nostr.land"),
	nostr.NormalizeURL("wss://purplepag.es"),
	nostr.NormalizeURL("wss://rbr.bio"),
	nostr.NormalizeURL("wss://relay.damus.io"),
	nostr.NormalizeURL("wss://relay.mostr.pub"),
	nostr.NormalizeURL("wss://relay.nostr.band"),
	nostr.NormalizeURL("wss://relay.nostr.bg"),
	nostr.NormalizeURL("wss://relay.nostrati.com"),
	nostr.NormalizeURL("wss://relay.orangepill.dev"),
	nostr.NormalizeURL("wss://relay.snort.social"),
	nostr.NormalizeURL("wss://universe.nostrich.land"),
}

func main() {
	ctx := context.Background()
	wg := sync.WaitGroup{}
	wg.Add(len(relays))

	for _, url := range relays {
		go func(url string) {
			defer wg.Done()

			relay, err := nostr.RelayConnect(ctx, url)
			if err != nil {
				fmt.Println(url, err)
				return
			}

			fmt.Println(url, "connected")

			sub, err := relay.Subscribe(ctx, nostr.Filters{nostr.Filter{Kinds: []int{10002}}})
			if err != nil {
				fmt.Println(url, err)
				return
			}

			fmt.Println(url, "subscribed")

			for {
				select {
				case <-sub.Events:

				case <-relay.ConnectionContext.Done():
					fmt.Println(url, "disconnected")
					return
				}
			}
		}(url)
	}

	wg.Wait()
}
```

**Comment by wozuo** [comment]
Ah yes you're right, the problem was outgoing pings. I think the last push should fix this.

And no this is the first time I'm using this library, so critical testing is very welcome! I'm also actively searching for alternatives to gorilla at the moment.

Also: Maybe we should include a way to manually set the compression level, right now it defaults to level 4.

**Comment by fiatjaf** [comment]
4 is fine I guess, but it still works if the server doesn't support compression, right?

**Comment by fiatjaf** [comment]
Yes, the last commit has fixed it.

**Comment by wozuo** [comment]
> 4 is fine I guess, but it still works if the server doesn't support compression, right?

Right now one needs to explicitly enable compression like so: `rl := &Relay{URL: NormalizeURL("wss://relay.damus.io"), EnableCompression: true}`. So your code above doesn't compress the messages. And if enableCompression is set to true and the server does not support compression, an error is returned. 

But maybe it would be better to enable compression by default for all connections and if the server does not support compression automatically fall back (we can check this after the handshake). This would be much simpler for users of the library. I'll implement this in a bit.

**Comment by fiatjaf** [comment]
Yes, please, that will be much better.

**Comment by fiatjaf** [comment]
I've enabled compression manually on my test here and that causes all relays to disconnect immediately.

**Comment by wozuo** [comment]
Hmmm.. does the `TestSubscribeEnableCompression` test work on your end? It uses compression to connect to the Damus relay and it should work.

**Comment by wozuo** [comment]
Alright, now the messages will be compressed whenever the relay supports it

**Comment by fiatjaf** [comment]
Hmm, something is still not great with the compression, but it's hard to know what:

This is using gorilla:
2023-05-05-174006_1174x1036_scrot

This is using your latest commit:
2023-05-05-174035_922x1080_scrot

**Comment by fiatjaf** [comment]
And this is running your previous commit with compression disabled:
2023-05-05-174222_1082x1073_scrot

**Comment by fiatjaf** [comment]
For some reason, gorilla doesn't like relay.snort.social, gobwas/uncompressed doesn't like universe.nostrich.land and gobwas/compressed doesn't like 6 other relays.

**Comment by wozuo** [comment]
Some servers for some reason send back uncompressed messages, even though permessage-deflate was negotiated during the handshake. Now we adapt on the fly to what the server decides to do.

**Comment by fiatjaf** [comment]
ahahah, this is absurd.

**Comment by fiatjaf** [comment]
Great, this has fixed basically everything in my stupid test.

**Comment by fiatjaf** [comment]
Are you working on something related to Nostr secretly?

**Comment by wozuo** [comment]
Ah great! Yes I'm working on a few Nostr projects, hopefully I'll be able to release some of them soon!

**Comment by fiatjaf** [comment]
Hmm, this is sending binary messages to relays, and for some reason some of them accept it, but they shouldn't.

**Comment by wozuo** [comment]
What kind of binary messages?

**Comment by fiatjaf** [comment]
Seems to be that way. All I know is that some relays, like nostr-rs-relay and, I think, nostream, are returning `NOTICES` saying they don't support binary messages. I glanced at the code but couldn't find the place where such opcodes are set.

**Comment by fiatjaf** [comment]
Fixed in fa001338251e8f37fcd8877774b055124d46e9ea.

**Comment by wozuo** [comment]
> Fixed in [fa00133](https://github.com/nbd-wtf/go-nostr/commit/fa001338251e8f37fcd8877774b055124d46e9ea).

Ah perfect, that's exactly the fix I wanted to propose

**Pull request merged**
