### PR TITLE
dedicating kind type and adding its methods.

### PR DESCRIPTION
**Pull request by kehiy**
I've made a new type `Kind` which is equal to `uint16`. it supports fixed numbers of all Kinds. but the `int` type is basically `int32` and `int64` based on the target device (as far as I know), which can hold bigger numbers and it's unnecessary. Also, some methods were added for getting the range of a kind which can help in the relay or maybe client Implementations.

Example: https://github.com/dezh-tech/immortal/blob/main/types/kind.go

### CODE REVIEW

**Comment by fiatjaf** [comment]
I don't like the extra cognitive load for very little gain, but maybe, let me think about it.

**Comment by kehiy** [comment]
@fiatjaf That's OK. We can remove the type itself, but keep the methods!

**Comment by kehiy** [comment]
do you think we should close this one? i'm trying to make another pr but I made this one on the master branch. so, it seems i'm limited now.

**Comment by kehiy** [comment]
I close this and open it on another branch.

**Pull request closed without merging**
