### PR TITLE
Remove context filed in subscription

### PR DESCRIPTION
**Pull request by shota3506**
Just a suggestion.
Feel free to close this PR if you want to avoid breaking the change in the public method.

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it.

https://pkg.go.dev/context

### CODE REVIEW

**Comment by fiatjaf** [comment]
Do you have a good reason for this or are you just blindly following the Golang docs?

**Comment by shota3506** [comment]
I saw Pool and Relay implementation and they also hold context. It looks better to keep it for consistency.

**Comment by fiatjaf** [comment]
We can hide the context inside a getter.

**Comment by fiatjaf** [comment]
The Golang standard library itself holds context in structs, like in `net/http` for example. I don't see a better way to do this here. This PR would just remove the important feature of having a subscription be canceled when a context expires.

**Pull request closed without merging**
