### PR TITLE
problem: can't unsub

### PR DESCRIPTION
**Pull request by stanstacks**
Not sure if you will like it or not but this is the simplest way I could see to fix the issue.

### CODE REVIEW

**Comment by fiatjaf** [comment]
Thank you. Not bad, but I think it would be better to return a function that closes the subscription instead of a channel that has to be closed, that is confusing.

Can you change it to be like that, please? Otherwise I can do it later.

**Comment by jraedisch** [comment]
Why return a function at all and not implement Unsub(subID) ranging over the Relays and Unsubscribe there?

(I just started reading into the code base and trying to learn.)

**Comment by fiatjaf** [comment]
Could be that too, I was thinking of doing that actually, but I think returning a function is better because it is more annoying and reminds the library user of closing his subscriptions, which they definitely should do.

**Comment by stanstacks** [comment]
I'll update it

**Pull request merged**
