### PR TITLE
fix heavy loop

### PR DESCRIPTION
**Pull request by mattn**
Sorry watching sub.EndOfStoredEvents in for loop make heavy loop if the chan is closed.

### CODE REVIEW

**Comment by mattn** [comment]
@fiatjaf I hope that this change will be merge soon because the impact of this bug is significant.

**Comment by fiatjaf** [comment]
Should we change the `EndOfStoredEvents` to not be closed when an EOSE is received, but instead just have something sent through it? And it's never closed?

**Comment by fiatjaf** [comment]
I don't understand the code in this function. Did I write it? Do we need this mutex? I think we don't.

**Comment by mattn** [comment]
>Should we change the EndOfStoredEvents to not be closed when an EOSE is received, but instead just have something sent through it? And it's never closed?

Yes, it's better i thinkg since most of people should do same mistake with me.

> I don't understand the code in this function. Did I write it?

No, I did.

> Do we need this mutex? I think we don't.

Yes, bool is thread safe. Pleaes change if you want.

**Comment by mattn** [comment]
@fiatjaf Could you please put new tag?

**Comment by fiatjaf** [comment]
> No, I did.

ahahah, ok, thank you. I really thought it had been me and that I was going crazy and forgetting about my code. I'm relieved to learn it was you then.

**Pull request merged**
